import nodemailer from 'nodemailer'
import dotenv from "dotenv"
dotenv.config()

// Create a transporter object that is responsible for sending emails
// It defines which email service to use and how to authenticate
const transporter = nodemailer.createTransport({
    // Specifies the email service provider (Gmail SMTP)
    service: "Gmail",

    // SMTP port for secure email sending (465 = SSL)
    port: 465,

    // true means emails will be sent using SSL encryption
    // (required when using port 465)
    secure: true,

    // Authentication details for the email account
    auth: {
        // Email address from which emails will be sent
        // Stored in environment variables for security
        user: process.env.EMAIL,

        // App Password generated from Gmail (not normal Gmail password)
        // Stored securely in environment variables
        pass: process.env.PASS,
    },
});

// transporter is later used to send emails like OTP, reset links, etc.

// Function to send OTP email for password reset
// `to`  → recipient email address
// `otp` → one-time password generated by the server
export const sendOtpMail = async (to, otp) => {

    // Send an email using the configured Nodemailer transporter
    await transporter.sendMail({

        // Sender email address (from environment variables)
        from: process.env.EMAIL,

        // Receiver email address
        to,

        // Subject line of the email
        subject: "Reset Your Password",

        // HTML content of the email
        // Includes the OTP and its expiry information
        html: `<p>Your OTP for password reset is <b>${otp}</b>. It expires in 5 minutes.</p>`
    });
};


// for sent DeliveryOtp
export const sendDeliveryOTPMail = async (user, otp) => {

    // Send an email using the configured Nodemailer transporter
    await transporter.sendMail({

        // Sender email address (from environment variables)
        from: process.env.EMAIL,

        // Receiver email address
        to:user.email,

        // Subject line of the email
        subject: "Delivery OTP",

        // HTML content of the email
        // Includes the OTP and its expiry information
        html: `<p>Your OTP for delivery is <b>${otp}</b>. It expires in 5 minutes.</p>`
    });
};



