import sgMail from '@sendgrid/mail';
import dotenv from "dotenv";
dotenv.config();

// Set SendGrid API key from environment variables
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

// Function to send OTP email for password reset
// `to`  → recipient email address
// `otp` → one-time password generated by the server
export const sendOtpMail = async (to, otp) => {
    try {
        const msg = {
            to, // Recipient email
            from: process.env.EMAIL, // Verified sender email in SendGrid
            subject: "Reset Your Password",
            html: `<p>Your OTP for password reset is <b>${otp}</b>. It expires in 5 minutes.</p>`
        };

        await sgMail.send(msg);
        console.log('OTP email sent successfully');
    } catch (error) {
        console.error('Error sending OTP email:', error);
        throw new Error('Failed to send OTP email');
    }
};

// Function to send Delivery OTP email
export const sendDeliveryOTPMail = async (user, otp) => {
    try {
        const msg = {
            to: user.email, // Recipient email
            from: process.env.EMAIL, // Verified sender email in SendGrid
            subject: "Delivery OTP",
            html: `<p>Your OTP for delivery is <b>${otp}</b>. It expires in 5 minutes.</p>`
        };

        await sgMail.send(msg);
        console.log('Delivery OTP email sent successfully');
    } catch (error) {
        console.error('Error sending delivery OTP email:', error);
        throw new Error('Failed to send delivery OTP email');
    }
};



